# Author: Mamun
# All rights reserved. Copyright (c)
version: '3.8'

services:
  app:
    image: laravel/php
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    labels:
      project: "laravel-app"
      environment: local
      company: " Inc"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - "9000"
    networks:
      - practice

#   node:
#     image: node:20  # Use latest LTS version
#     container_name: laravel_node
#     working_dir: /var/www
#     volumes:
#       - .:/var/www
#     command: tail -f /dev/null

  node:
    image: node:22.12.0-alpine
    container_name: laravel_node
    working_dir: /var/www/frontend
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/var/www/frontend
      - node_modules:/var/www/frontend/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app
    networks:
      - practice
    # volumes:
    #   - type: bind
    #     source: ./frontend
    #     target: /app
    #     consistency: cached
    #   - type: volume
    #     source: node-module-volume
    #     target: /app/node_modules

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    tty: true
    platform: linux/amd64
    labels:
      project: "laravel-practice"
      environment: local
      company: " Inc"
    environment:
      MYSQL_DATABASE: laravel_test
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - practice
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

    #   queue:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     container_name: laravel_queue
    #     restart: always
    #     working_dir: /var/www
    #     command: php artisan queue:work
    #     volumes:
    #         - .:/var/www
    #     depends_on:
    #         - db
    #         - app
    #     env_file:
    #         - .env

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - 5000:80
      - 5001:81
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- ./docker/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      #- ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - node
    networks:
      - practice

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: practice_phpmyadmin
    restart: always
    ports:
      - 5010:80
    labels:
      project: "laravel-practice"
      environment: local
      company: " Inc"
    environment:
      UPLOAD_LIMIT: 102400
      HIDE_PHP_VERSION: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - db
    links:
      - db
    networks:
      - practice


#Docker Networks
networks:
  practice:
    driver: bridge

volumes:
  dbdata:
    driver: local
  node_modules:
