name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel_test_db
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    strategy:
      fail-fast: true
      matrix:
        php: [8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, pcov, uopz
          coverage: pcov

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --ignore-platform-reqs

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Copy environment file
        run: cp .env.test .env

      - name: Override database host for GitHub Actions
        run: sed -i 's/DB_HOST=db/DB_HOST=127.0.0.1/' .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations and Seed database
        env:
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: ''
        run: php artisan migrate:fresh --seed

      # - name: Execute tests
      #   env:
      #     DB_HOST: 127.0.0.1
      #     DB_USERNAME: root
      #     DB_PASSWORD: ''
      #   run: ./vendor/bin/phpunit
      - name: Execute tests with coverage
        env:
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: ''
        run: ./vendor/bin/phpunit --coverage-clover coverage.xml --coverage-text --colors=never
      # --- ADD THIS DEBUGGING STEP ---
      - name: Verify coverage file exists
        run: ls -la

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: phpunit
          verbose: true
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # - name: Create PR comment with test coverage
      #   if: github.event_name == 'pull_request' && hashFiles('coverage.xml') != ''
      #   uses: lucassabreu/comment-coverage-clover@v0.3.0
      #   with:
      #     clover-file: coverage.xml
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
